[package]
name = "zoi-system"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "zoi_system"

[dependencies]
zoi-core.workspace = true
zoi-project.workspace = true
zoi-install.workspace = true
anyhow.workspace = true
colored.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
mlua.workspace = true
aes-gcm.workspace = true
rand.workspace = true
argon2.workspace = true
base64.workspace = true
tempfile.workspace = true

[dev-dependencies]
