use crate::config::FilesystemConfig;

pub fn generate_fstab(filesystems: &[FilesystemConfig]) -> String {
    let mut fstab =
        String::from("# /etc/fstab: static file system information.\n# Generated by ZoiOS\n\n");
    fstab.push_str(
        format!(
            "{:<30} {:<15} {:<10} {:<20} {:<5} {:<5}\n",
            "# <file system>", "<mount point>", "<type>", "<options>", "<dump>", "<pass>"
        )
        .as_str(),
    );

    for fs in filesystems {
        let options = fs.options.as_deref().unwrap_or("defaults");
        fstab.push_str(
            format!(
                "{:<30} {:<15} {:<10} {:<20} {:<5} {:<5}\n",
                fs.device,
                fs.mount,
                fs.fs_type,
                options,
                "0",
                if fs.mount == "/" { "1" } else { "2" }
            )
            .as_str(),
        );
    }
    fstab
}
