stages:
  - test
  - build
  - package
  - release

check_build:
  stage: test
  image: rust:latest
  before_script:
    - apt-get update -y && apt-get install -y gcc 
  script:
    - echo "Running a quick compilation check..."
    - cargo check --verbose
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH

build:linux:
  stage: build
  image: rust:latest
  before_script:
    - dpkg --add-architecture arm64
    - dpkg --add-architecture armhf
    - apt-get update -y && apt-get install -y build-essential gcc gcc-aarch64-linux-gnu libssl-dev pkg-config libssl-dev:arm64 openssl libssl-dev:armhf gcc-mingw-w64-x86-64
  script:
    - echo "Building Linux targets (amd64, arm64) and Windows (amd64)..."
    - chmod +x ./build/build-linux.sh
    - ./build/build-linux.sh
  artifacts:
    paths:
      - ./build/release/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG

build:macos:
  stage: build
  tags:
    - saas-macos-medium-m1
  image: macos-15-xcode-16
  before_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source ~/.cargo/env
  script:
    - echo "Building macOS targets (amd64, arm64)..."
    - chmod +x ./build/build-macos.sh
    - ./build/build-macos.sh
  artifacts:
    paths:
      - ./build/release/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG

package:archive:
  stage: package
  image: ubuntu:latest
  before_script:
    - apt-get update -y && apt-get install -y p7zip-full tar
  script:
    - echo "Aggregating build artifacts..."
    - echo "Contents of the release directory:"
    - ls -lR ./build/release/
    - echo "Running archive script..."
    - chmod +x ./build/archive.sh
    - ./build/archive.sh
    - echo "Archiving complete."
  needs:
    - build:linux
    - build:macos
  artifacts:
    paths:
      - ./build/archived/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  needs:
    - package:archive
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  script:
    - echo "Creating GitLab Release for tag $CI_COMMIT_TAG..."
    - glab release create "$CI_COMMIT_TAG" ./build/archived/* --title "$CI_COMMIT_TAG_MESSAGE" --notes "Official release for Zoi version $CI_COMMIT_TAG"
    - echo "Release created successfully."
  rules:
    - if: $CI_COMMIT_TAG
