stages:
  - test
  - build
  - release

check_build:
  stage: test
  image: rust:latest
  
  before_script:
    - apt-get update -y && apt-get install -y gcc
  
  script:
    - echo "Running a quick compilation check..."
    - cargo check --verbose
  
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH

build_job:
  stage: build
  image: rust:latest
  
  before_script:
    - apt-get update -y && apt-get install -y make gcc
  
  script:
    - cargo install cross --git https://github.com/cross-rs/cross
    - echo "Building Zoi for release..."
    - chmod +x ./build/*.sh
    - ./build/build-all.sh
    - ./build/archive.sh
    - echo "Build and archiving complete."
    - ls -l ./build/build-release/
  
  artifacts:
    paths:
      - ./build/build-release/
    expire_in: 1 week

  rules:
    - if: $CI_COMMIT_TAG

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  needs:
    - build_job

  script:
    - echo "Creating GitLab Release for tag $CI_COMMIT_TAG..."
    - glab release create "$CI_COMMIT_TAG" ./build/build-release/* --title "Release $CI_COMMIT_TAG" --notes "Official release for Zoi version $CI_COMMIT_TAG"
    - echo "Release created successfully."
  
  rules:
    - if: $CI_COMMIT_TAG
