# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[remote.gitlab]
owner = "zillowe/zillwen/zusty"
repo = "zoi"

[changelog]
header = """
# Changelog

You can install any of these versions: `zoi upgrade --tag --force <tag>`

To install Zoi: `curl -fsSL https://zillowe.pages.dev/scripts/zoi/install.sh | bash`, [more installation methods](https://zillowe.qzz.io/docs/zds/zoi).

"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits | unique(attribute="message") %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""
trim = true
render_always = true
postprocessors = [
    # Replace the placeholder <REPO> with a URL.
    #{ pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" },
]
output = "CHANGELOG.md"

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
    { message = "(?i)^Docs", skip = true },
    { message = "(?i)^CI", skip = true },
    { message = "(?i)^Release", skip = true },
    { message = "(?i)^Git", skip = true },
    { message = "(?i)^Ignore", skip = true },

    { message = "^Merge", group = "⏩ Merged" },
    { message = "^Build", group = "🛠️ Build" },
    { message = "^Feat", group = "✨ Features" },
    { message = "^Fix", group = "🩹 Bug Fixes" },
    { message = "^Perf", group = "⚡ Performance" },
    { message = "^Refactor", group = "♻️ Refactor" },
    { message = "^Style", group = "🎨 Styling" },
    { message = "^Test", group = "🧪 Testing" },
    { message = "^Revert", group = "⏪ Revert" },
    { message = "^Deps", group = "🛡️ Dependencies" },
    { message = "^Cleanup", group = "🧹 Cleanup" },
    { message = "^Security", group = "🔒 Security" },
    { message = "^I18n", group = "🌐 Internationalization" },
    { message = "^Migrate", group = "➡️ Migrations" },
    { message = "^SEO", group = "🔍 SEO" },
    { message = "^AI", group = "🧠 AI" },
    { message = "^Data", group = "📊 Data" },
    { message = "^Config", group = "🔧 Configuration" },
    { message = "^UX", group = "🎯 UX" },
    { message = "^Struct", group = "🏗️ Structure" },
    { message = "^Auth", group = "🔐 Authentication" },
    { message = "^Track", group = "📈 Tracking" },
    { message = "^API", group = "📋 API" },

    { message = ".*", group = "💼 Other" },
]
link_parsers = [
    { pattern = "#([0-9]+)", href = "https://gitlab.com/zillowe/zillwen/zusty/zoi/-/issues/$1", text = "#$1" },
    { pattern = "!([0-9]+)", href = "https://gitlab.com/zillowe/zillwen/zusty/zoi/-/merge_requests/$1", text = "!$1" },
]
filter_commits = false
sort_commits = "newest"
recurse_submodules = false
