# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[remote.gitlab]
owner = "zillowe/zillwen/zusty"
repo = "zoi"

[changelog]
header = """
# Changelog

You can install any of these versions: `zoi upgrade --tag --force <tag>`

To install Zoi: `curl -fsSL https://zillowe.pages.dev/scripts/zoi/install.sh | bash`, [more installation methods](https://zillowe.qzz.io/docs/zds/zoi).

"""
body = """
{% if version %}\
    ## [{{ version | replace_regex(from="^([A-Za-z]+)-", to="${1}. ") | replace_regex(from="-([0-9.]+)$", to=" ${1}") | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits | unique(attribute="message") %}
        - [`{{ commit.id | truncate(length=8, end='') }}`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/{{ commit.id }}) {% if commit.scope %}*({{ commit.scope }})* {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}

"""
footer = """
## [Dev. Beta 1.2.1]

### ♻️ Refactor

- [`f1badc5a`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/f1badc5a2fa3bddf18e57fb052e90c1b9bec49c8) *info* Source system details from configuration.

### 🩹 Bug Fixes

- [`b8b0961c`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/b8b0961c9b00b3038c2a9aaa1bf4e4b6fb94c6b6) *cmd* Removed redundant error print and unused import.

## [Dev. Beta 1.2.0]

### ✨ Features

- [`11d0f583`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/11d0f583c6ee100d16c637f1c26bcd71db700922) *env* Made command interactive.
- [`bb9f64ff`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/bb9f64ffc6aa5e2b4b9de240c9ff5051c0aaf198) *env* Implemented Go version manager.

## [Dev. Beta 1.1.0]

### ✨ Features

- [`151f2f45`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/151f2f4588e1a1a956202b69e449b7344a8fde14) *update* Added --force flag for reinstallation.
- [`cee2da83`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/cee2da8374f56648b6017cd1d4a5f7a05a366022) *set* Added interactive mode for config values.
- [`6fc339b4`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/6fc339b408a18b11c66352d5ed587b28376ccc78) *run* Allowed interactive command selection.

## [Dev. Beta 1.0.0]

### ♻️ Refactor

- [`a2b4f4a5`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/a2b4f4a5cc65802f0d54e1bca24bca1b21f84619) Moved to Cobra for command-line tool and Viper for config.

## [Dev. Alpha 3.2.0]

### ✨ Features

- [`7c35bd9f`](https://gitlab.com/zillowe/zillwen/zusty/zoi/-/commit/7c35bd9fcbaf8d772ea9fdc9641a507f3d45893b) Added update packages before installing.

## [Dev. Alpha 3.1.0]

### ✨ Features

- Added a bunch of features.

## [Dev. Alpha 3.0.0]

### ✨ Features

- Added `uninstall` subcommand to `zoi vm`.
- Allows users to remove specific installed language versions (e.g. `zoi vm uninstall go@1.20.0`).

### ♻️ Refactor

- Improved main `zoi` help message clarity.
- Refined command descriptions in the global `zoi help` output for better readability and understanding.

## [Dev. Alpha 2.0.0]

### ✨ Features

- Added version managing command.
- Added Go and Python version managing.

## [Dev. Alpha 1.0.0]

### ♻️ Refactor

- Major code rewrite and reformat.
- Moved the commands to a `commands` folder.
- Better code structure and better code overall.

## [Dev. Pre-Alpha 2.4.0]

### 🛠️ Build

- Added update command that update Zoi.
- Added build all script that build arm64/amd64 versions of linux/macos/windows.

## [Dev. Pre-Alpha 2.3.0]

### ✨ Features

- Added install command that install system packages.

## [Dev. Pre-Alpha 2.2.0]

### ✨ Features

- Added set command that set the apps url in a config file.

## [Dev. Pre-Alpha 2.1.0]

### ✨ Features

- Added check command that checks network and golang + git versions.

## [Dev. Pre-Alpha 2.0.0]

### 🛠️ Build

- Added build scripts for Linux/MacOS and Windows.
- Moved from NodeJS to Golang.

### ➡️ Migrations

- Command usage for make changed from json file to yaml.

## [Dev. Pre-Alpha 1.4.0]

- Making the structure better.

## [Dev. Pre-Alpha 1.3.0]

- Adding the ability to create apps from a local json file.

## [Dev. Pre-Alpha 1.2.0]

- Making the app fetch the frameworks and apps from the website.

## [Dev. Pre-Alpha 1.1.0]

- Another rewriting some of the files.
- Rewriting some of the files.

## [Dev. Pre-Alpha 1.0.0]

- Adding the ability to create new apps and frameworks, adding Ruby on Rails support.
- The main foundation of the project.
- Init.
"""
trim = true
render_always = true
postprocessors = [
    # Replace the placeholder <REPO> with a URL.
    #{ pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" },
]
output = "CHANGELOG.md"

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
    { message = "(?i)^Docs", skip = true },
    { message = "(?i)^CI", skip = true },
    { message = "(?i)^Release", skip = true },
    { message = "(?i)^Git", skip = true },
    { message = "(?i)^Ignore", skip = true },

    { message = "^Merge", group = "⏩ Merged" },
    { message = "^Build", group = "🛠️ Build" },
    { message = "^Feat", group = "✨ Features" },
    { message = "^Fix", group = "🩹 Bug Fixes" },
    { message = "^Perf", group = "⚡ Performance" },
    { message = "^Refactor", group = "♻️ Refactor" },
    { message = "^Style", group = "🎨 Styling" },
    { message = "^Test", group = "🧪 Testing" },
    { message = "^Revert", group = "⏪ Revert" },
    { message = "^Deps", group = "🛡️ Dependencies" },
    { message = "^Cleanup", group = "🧹 Cleanup" },
    { message = "^Security", group = "🔒 Security" },
    { message = "^I18n", group = "🌐 Internationalization" },
    { message = "^Migrate", group = "➡️ Migrations" },
    { message = "^SEO", group = "🔍 SEO" },
    { message = "^AI", group = "🧠 AI" },
    { message = "^Data", group = "📊 Data" },
    { message = "^Config", group = "🔧 Configuration" },
    { message = "^UX", group = "🎯 UX" },
    { message = "^Struct", group = "🏗️ Structure" },
    { message = "^Auth", group = "🔐 Authentication" },
    { message = "^Track", group = "📈 Tracking" },
    { message = "^API", group = "📋 API" },

    { message = ".*", group = "💼 Other" },
]
link_parsers = [
    { pattern = "#([0-9]+)", href = "https://gitlab.com/zillowe/zillwen/zusty/zoi/-/work_items/$1", text = "#$1" },
    { pattern = "!([0-9]+)", href = "https://gitlab.com/zillowe/zillwen/zusty/zoi/-/merge_requests/$1", text = "!$1" },
]
filter_commits = false
sort_commits = "newest"
recurse_submodules = false
