# rustfmt.toml
# See https://rust-lang.github.io/rustfmt/ for configuration options

# The default width is 100, but we'll be explicit.
max_width = 100

# Use a more vertical layout for better readability.
use_small_heuristics = "Max"

# Reorder imports to be alphabetical.
reorder_imports = true

# Don't reorder `mod` statements.
reorder_modules = false
