on: [push]
jobs:
  build-and-test:
    runs-on: codeberg-tiny-lazy
    strategy:
      matrix:
        go-version: ["1.21", "1.24"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...

      - name: Verify build
        run: go build -v .
