name: ldconfig
description: Configuring dynamic linker run-time bindings...
platforms: ["linux"]
trigger:
  dirs: ["usr/lib"]
  paths: ["etc/ld.so.conf", "etc/ld.so.conf.d/*", "usr/lib/ld.so.conf.d/*"]
  operation: ["install", "upgrade", "remove"]
action:
  when: PostTransaction
  exec: "/usr/bin/ldconfig -r /"
