name: update-desktop-database
description: Updates the desktop entry database.
platforms: ["linux"]
trigger:
  paths:
    - "usr/share/applications/*.desktop"
  operation: ["install", "upgrade", "remove"]
action:
  when: PostTransaction
  exec: update-desktop-database -q
